on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
jobs:
  gradle:
    runs-on: [ deere-ubuntu-latest ]

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5

      - name: Execute Gradle build
        run: gradle clean check build --info -x dependencyCheckAnalyze

      - name: Cache jar files
        uses: actions/cache@v3
        with:
          path: ./build/libs/*.jar
          key: gradle-${{ github.run_id }}
